version: '3.8'

services:
  web:
    build: ./web
    command: gunicorn --bind 0.0.0.0:5000 run:app
    expose:
      - "5000"
    volumes:
      - ./logs:/src/logs
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      # - "443:443"
    # volumes:
        # - ./nginx/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
        # - ./nginx/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
        # - ./nginx/conf.d:/etc/nginx/conf.d
        # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web