version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    # volumes:
        # - ./nginx/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
        # - ./nginx/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
        # - ./nginx/conf.d:/etc/nginx/conf.d
        # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web